server:
  port: 8020

spring:
  application:
    name: gateway8020
  profiles:
    active: work
    include: eureka
  #  gateway配置第二版
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心发现服务，动态创建路由
      routes:
        - id: payment_payment  #全局唯一
          uri: lb://payment8001   #微服务名称
          predicates:
            - Path=/payment/**
            - After=2023-12-21T10:37:19.842+08:00[Asia/Shanghai]
            - Cookie=username,zjy  #多组cookie
            - Cookie=pwd,123
            - Method=GET,POST
          filter:
            -
        - id: payment_paymentHystrix  #全局唯一
          uri: lb://payment8001  #微服务名称
          predicates:
            - Path=/paymentHystrix/**

#  gateway 配置第一版
#  cloud:
#    gateway:
#      routes:
#        - id: payment_payment  #全局唯一
#          uri: http://localhost:8001   #匹配后转发的地址
#          predicates:
#            - Path=/payment/**
#        - id: payment_paymentHystrix  #全局唯一
#          uri: http://localhost:8001
#          predicates:
#            - Path=/paymentHystrix/**

