spring:
  profiles:
    active: pve
    include: mysql,eureka
  application:
    name: order8010


server:
  port: 8010

ribbon:
  ReadTimeout: 5000 # 读取资源超时时间 默认时间为1s
  ConnectTimeout: 5000 # 建立链接超时时间

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.common.entities

logging:
  level:
    tracer: trace
    com.legendyun.payment.dao: DEBUG
    com.legendyun.order.service.feign.PaymentFeignService: DEBUG
    com.legendyun.order.service.feign.PaymentFeignHystrixService: DEBUG

#开启feign对hystrix的支持
feign:
  hystrix:
    enabled: true