spring:
  profiles:
    active: work
    include: mysql,eureka
  application:
    name: payment8001

server:
  port: 8001

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.legendyun.payment.entities  # mapping中自动省略自定义实体 的全路径
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    tracer: trace
    com.legendyun.payment.dao: DEBUG

management:
  endpoints:
    web:
      exposure:
        exclude: '*'