mysql:
  url: "192.168.3.110:13306/mall-paymentdb"
  username: root
  password: zjy123456

eureka-server:
  defaultZone: "http://192.168.3.111:8761/eureka" #单机
#  defaultZone: "http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka" #集群
zookeeper:
  url: "192.168.3.111:2181"

consul:
  url: "192.168.3.111"